export const JUSTIFY = [
  "justify-start",
  "justify-end",
  "justify-center",
  "justify-around",
  "justify-between",
  "justify-evenly",
] as const;

export const ALIGN = [
  "items-start",
  "items-end",
  "items-center",
  "items-stretch",
  "items-baseline",
] as const;

export const FLEX_DIRECTION = [
  "flex-row",
  "flex-column",
  "flex-row-reverse",
  "flex-column-reverse",
] as const;

export const FONT_SIZES = [
  "text-heading-one",
  "text-heading-two",
  "text-heading-three",
  "text-heading-four",
  "text-body",
  "text-body-small",
  "text-button",
  "text-caption",
] as const;

export const FONT = ["font-Manrope", "font-Rebond"] as const;

export const COLORS = [
  "primary-100",
  "primary-dark",
  "primary-80",
  "primary-60",
  "primary-40",
  "primary-20",
  "primary-10",
  "primary-5",
  "secondary-100",
  "secondary-dark",
  "secondary-80",
  "secondary-60",
  "secondary-40",
  "secondary-20",
  "secondary-10",
  "secondary-5",
  "black-100",
  "black-dark",
  "black-80",
  "black-60",
  "black-40",
  "black-20",
  "black-10",
  "black-5",
  "white",
  "success-100",
  "success-darker",
  "success-lighter",
  "error-default",
  "error-darker",
  "error-lighter",
  "warning-default",
  "warning-darker",
  "warning-lighter",
] as const;

export const TEXT_COLORS = [
  "text-primary-100",
  "text-primary-dark",
  "text-primary-80",
  "text-primary-60",
  "text-primary-40",
  "text-primary-20",
  "text-primary-10",
  "text-primary-5",
  "text-secondary-100",
  "text-secondary-dark",
  "text-secondary-80",
  "text-secondary-60",
  "text-secondary-40",
  "text-secondary-20",
  "text-secondary-10",
  "text-secondary-5",
  "text-black-100",
  "text-black-dark",
  "text-black-80",
  "text-black-60",
  "text-black-40",
  "text-black-20",
  "text-black-10",
  "text-black-5",
  "text-white",
  "text-success-100",
  "text-success-darker",
  "text-success-lighter",
  "text-error-default",
  "text-error-darker",
  "text-error-lighter",
  "text-warning-default",
  "text-warning-darker",
  "text-warning-lighter",
] as const;

export const BG_COLORS = [
  "text-primary-100",
  "bg-primary-dark",
  "bg-primary-80",
  "bg-primary-60",
  "bg-primary-40",
  "bg-primary-20",
  "bg-primary-10",
  "bg-primary-5",
  "bg-secondary-100",
  "bg-secondary-dark",
  "bg-secondary-80",
  "bg-secondary-60",
  "bg-secondary-40",
  "bg-secondary-20",
  "bg-secondary-10",
  "bg-secondary-5",
  "bg-black-100",
  "bg-black-dark",
  "bg-black-80",
  "bg-black-60",
  "bg-black-40",
  "bg-black-20",
  "bg-black-10",
  "bg-black-5",
  "bg-white",
  "bg-success-100",
  "bg-success-darker",
  "bg-success-lighter",
  "bg-error-default",
  "bg-error-darker",
  "bg-error-lighter",
  "bg-warning-default",
  "bg-warning-darker",
  "bg-warning-lighter",
] as const;
